---
kind: pipeline
name: default

steps:
  - name: build-demo
    image: plugins/docker
    settings:
      repo: patrickjahns/nuclio-symfony-demo
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master